services:
  db:
    image: mariadb:10.11
    container_name: rytkoset-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rytkoset_wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  joomla-db:
    image: mariadb:10.11
    container_name: rytkoset-joomla-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla_pass
    volumes:
      - joomla_db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rytkoset-wp
    depends_on:
      - db
      - joomla-db
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: rytkoset_wp
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
  joomla_db_data:
